### ISSUE TITLE
helper "error" raises error when params include :type key

### ISSUE THREAD

**Issue by havilchis** [pabloh/pathway#40]
Inside the documentation, in the **Error objects** section, the example code suggest write something like this...

#### Code with error
 
```ruby
# frozen_string_literal: true

require "pathway"

class CreateNugget < Pathway::Operation
  def call(input)
    error(type: :validation, message: 'Invalid input', details: [])
  end
end

CreateNugget.new.call("something")
```
raise the following error:
```bash
$ ruby app.rb 
Traceback (most recent call last):
        4: from app.rb:11:in `<main>'
        3: from app.rb:17:in `call'
        2: from /home/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/pathway-0.11.1/lib/pathway.rb:116:in `error'
        1: from /home/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/pathway-0.11.1/lib/pathway.rb:116:in `new'
/home/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/pathway-0.11.1/lib/pathway.rb:40:in `initialize': undefined method `to_sym' for {:type=>:validation, :message=>"Invalid input", :details=>[]}:Hash (NoMethodError)
Did you mean?  to_s
               to_set
```

#### Code without error

Removing the :type key and leaving only the value as first param the code run as normal

```ruby
# frozen_string_literal: true

require "pathway"

class CreateNugget < Pathway::Operation
  def call(input)
    error(:validation, message: 'Invalid input', details: [])
  end
end

result = CreateNugget.new.call("something")

if result.failure?
  result.error.type #=> validation
  result.error.message #=> "Invalid input"
end
```

I don't know if I was forgot something or if this a outdated section in the README.

**Comment by pabloh** [comment]
Thanks for noticing this, the validation was out of date, I'll push an update.
